### ISSUE TITLE
Incorrect project directory

### ISSUE THREAD

**Issue by christianadr** [zhrssh/sci-toolkit#1]
Accessing PROJECT_DIR from globals results to path to environment being shown. (Refer to the image below)

![image](https://github.com/zhrssh/sci-template/assets/107937742/00f48668-fcf1-46b9-a78f-3a8355c262c2)

**Comment by zhrssh** [comment]
Bug should be fixed now.

![image](https://github.com/zhrssh/sci-template/assets/98146850/359114f8-7efd-415f-8989-14ed9ab9161d)
